version: '3'
services:
  selenium-chrome1:
    image: selenium/standalone-chrome
    container_name: selenium-chrome1
    ports:
      - "4444:4444"

  test-runner1:
    build: .
    container_name: test-runner1
    depends_on:
      - selenium-chrome1
    environment:
      - SELENIUM_HOST=selenium-chrome1
